server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud/spring-cloud-config-samples.git
          clone-on-start: true
