server:
  port: 8084

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true



#  Eureka version 4.0.0 onwards, which is being used in Spring Cloud 2022.0.0,
#  you do not need to explicitly register using the annotation
#  @EnableEurekaClient It automatically gets registered as client if spring-cloud-starter-netflix-eureka-client
#  is on the class path.