spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path= /hotels/**, /staffs/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path= /ratings/**
  main:
    web-application-type: reactive
server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
